const FLOOR_SOURCES=Object.freeze({
  '1F':Object.freeze({mode:'module',moduleId:'1F'}),
  'Dorms':Object.freeze({mode:'module',moduleId:'Dorms'}),
  '2F':Object.freeze({mode:'module',moduleId:'2F'}),
  '3F':Object.freeze({mode:'module',moduleId:'3F'})
});
const FLOOR_CONTRACT_VERSION='1.0.0';
const FLOOR_MESSAGES=Object.freeze({READY:'MAP_FLOOR_READY',SELECTED:'MAP_FLOOR_SELECTED',RESET_PANEL:'MAP_FLOOR_RESET_PANEL',ACTION:'MAP_FLOOR_REQUEST_ACTION',SELECT:'MAP_FLOOR_SELECT',CLEAR_SELECTION:'MAP_FLOOR_CLEAR_SELECTION',ACTIVATE:'MAP_FLOOR_ACTIVATE'});
let current='1F', selected=null, currentRooms=[], currentFloorMeta=null;
const frame=document.getElementById('floorFrame'), moduleHost=document.getElementById('floorModuleHost'), roomList=document.getElementById('roomList'), search=document.getElementById('search');
function cls(s){return s==='restricted'?'restricted':s==='locked'?'locked':s==='occupied'?'occupied':'open'}
function resetPanel(f,msg,status){document.getElementById('roomTitle').textContent=f;const tag=document.getElementById('roomStatus');tag.textContent=status||(f==='Dorms'?'Directory':f==='1F'?'Open':'Pending');tag.className='tag '+((status||'').toLowerCase()==='directory'?'occupied':cls((status||'').toLowerCase()));document.getElementById('roomDesc').textContent=msg;document.getElementById('profileBox').innerHTML='';}
function activeSource(){return FLOOR_SOURCES[current]||null;}
function isModuleFloor(){return activeSource()?.mode==='module';}
function postToFloor(type,extra={}){if(isModuleFloor()||!frame.contentWindow)return;frame.contentWindow.postMessage(Object.assign({type,floor:current,contractVersion:FLOOR_CONTRACT_VERSION},extra),'*');}
// M.S.13: canonical room destinations remain in map-shared/room-registry.js.
// M.S.14: floor JavaScript modules own layout/data only; the shell renders them.
function activeRoomLauncher(r){const entry=window.SHPRoomRegistry?.resolve(r,current);return entry&&entry.launchEnabled?{roomId:entry.roomId,label:entry.launchLabel||'Enter Room',entry:entry.entry}:null;}
function roomEntryContext(){return {source:'map',returnTarget:'map',floor:current,locationId:'school-map',spawnId:null};}
function requestOpenRoom(roomId){if(!roomId)return;const payload={type:'SHP_OPEN_ROOM',roomId,context:roomEntryContext()};if(window.parent!==window){window.parent.postMessage(payload,'*');return;}const entry=window.SHPRoomRegistry?.get(roomId);if(!entry?.entry)return;const q=`?shpSource=map&shpReturn=map&shpFloor=${encodeURIComponent(current)}&shpLocation=school-map`;window.location.href=entry.entry+q;}
function syncFloorSelection(r){if(isModuleFloor()){window.SHPFloorModuleRenderer?.select(moduleHost,r.roomId||null,r.name||null);}else{postToFloor(FLOOR_MESSAGES.SELECT,{roomId:r.roomId||null,roomName:r.name});}}
function selectRoom(r,fromFloor=false){if(!r||!r.name)return;selected=r.roomId||r.name;document.getElementById('roomTitle').textContent=r.name;const tag=document.getElementById('roomStatus');tag.textContent=r.status||'open';tag.className='tag '+cls(r.status);document.getElementById('roomDesc').textContent=r.desc||'No description yet.';const box=document.getElementById('profileBox');const launcher=activeRoomLauncher(r);const dormMailboxRoomId=r.roomId||(current==='Dorms'&&r.name?`${String(r.name).trim().toLowerCase()}-dorm`:'');const dormMailboxCharacter=current==='Dorms'?window.SHPDormMailbox?.characterForRoom(dormMailboxRoomId):'';let html='';if(r.url)html+=`<a class="profile-link" href="${r.url}" target="_blank" rel="noopener noreferrer">Open Notion Profile</a>`;if(launcher)html+=`<button type="button" class="visit-dorm-btn" id="visitActiveRoom">${launcher.label}</button>`;if(dormMailboxCharacter)html+=`<button type="button" class="visit-dorm-btn" id="openDormMailbox">✉ Mailbox</button>`;box.innerHTML=html;if(launcher&&document.getElementById('visitActiveRoom'))document.getElementById('visitActiveRoom').onclick=()=>requestOpenRoom(launcher.roomId);if(dormMailboxCharacter&&document.getElementById('openDormMailbox'))document.getElementById('openDormMailbox').onclick=()=>window.SHPDormMailbox.openForCharacter(dormMailboxCharacter);if(current==='Dorms'&&dormMailboxRoomId&&window.SHPDormCompanion){const selectedKey=selected;window.SHPDormCompanion.findForRoom(dormMailboxRoomId).then(item=>{if(!item||selected!==selectedKey)return;const b=document.createElement('button');b.type='button';b.className='visit-dorm-btn';b.id='openDormCompanion';b.textContent='✦ Companion';b.onclick=()=>window.SHPDormCompanion.openForRoom(dormMailboxRoomId);box.appendChild(b);}).catch(()=>{});}if(!fromFloor)syncFloorSelection(r);}
function renderList(){const q=search.value.trim().toLowerCase();roomList.innerHTML='';currentRooms.filter(r=>String(r.name||'').toLowerCase().includes(q)).forEach(r=>{let b=document.createElement('button');b.className='room-btn';b.textContent=r.name;b.dataset.roomId=r.roomId||'';b.onclick=()=>selectRoom(r);roomList.appendChild(b);})}
function activateModuleFloor(source){const def=window.SHPFloorModuleRegistry?.get(source.moduleId);if(!def){resetPanel(current,'Could not load '+current+' floor module.','Error');return;}frame.style.display='none';moduleHost.classList.add('active');currentRooms=def.rooms.slice();currentFloorMeta={id:def.id,label:def.label||def.id,description:def.description||'',status:def.status||'Open'};window.SHPFloorModuleRenderer.render(moduleHost,def,{onSelect:r=>selectRoom(r,true)});resetPanel(current,currentFloorMeta.description,currentFloorMeta.status);renderList();}
function activateIframeFloor(source){moduleHost.classList.remove('active');moduleHost.innerHTML='';frame.style.display='block';frame.src=source.src;}
function loadFloor(f){const source=FLOOR_SOURCES[f];if(!source)return;current=f;selected=null;currentRooms=[];currentFloorMeta=null;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.floor===f));document.getElementById('exploreDormHall').style.display=f==='Dorms'?'inline-block':'none';search.value='';roomList.innerHTML='';resetPanel(f,f==='Dorms'?'Loading dorm directory…':f==='1F'?'Loading first floor…':'Loading '+f+'…','Pending');if(source.mode==='module')activateModuleFloor(source);else activateIframeFloor(source);}
function acceptFloorMessage(event,msg){return !isModuleFloor()&&event.source===frame.contentWindow&&msg&&typeof msg==='object'&&msg.floor===current;}
window.addEventListener('message',event=>{const msg=event.data;if(!msg||typeof msg!=='object')return;
 if(acceptFloorMessage(event,msg)){
   if(msg.type===FLOOR_MESSAGES.READY){currentRooms=Array.isArray(msg.rooms)?msg.rooms.filter(r=>r&&r.name):[];currentFloorMeta=msg.meta&&typeof msg.meta==='object'?msg.meta:{id:current,label:current,description:msg.description||'',status:msg.status||'Open'};resetPanel(current,msg.description||currentFloorMeta.description||'',msg.status||currentFloorMeta.status);renderList();postToFloor(FLOOR_MESSAGES.ACTIVATE,{meta:currentFloorMeta});return;}
   if(msg.type===FLOOR_MESSAGES.SELECTED&&msg.room){selectRoom(msg.room,true);return;}
   if(msg.type===FLOOR_MESSAGES.RESET_PANEL){resetPanel(current,msg.description||currentFloorMeta?.description||'',msg.status||currentFloorMeta?.status);search.value='';renderList();return;}
   if(msg.type===FLOOR_MESSAGES.ACTION){window.dispatchEvent(new CustomEvent('shp-map-floor-action',{detail:{floor:current,action:msg.action,payload:msg.payload||{}}}));return;}
   if(msg.type==='MAP_FLOOR_REQUEST_JACEY_EXIT'){if(new URLSearchParams(location.search).get('mode')==='handbook'&&window.parent!==window)window.parent.postMessage({type:'shp:request-exit-jacey'},'*');else postToFloor('MAP_FLOOR_CLOSE_JACEY');return;}
 }
 if(event.source!==frame.contentWindow&&msg.type==='shp:show-jacey-room'){if(current!=='Dorms')loadFloor('Dorms');setTimeout(()=>postToFloor('MAP_FLOOR_OPEN_JACEY'),50);return;}
 if(event.source!==frame.contentWindow&&msg.type==='shp:show-dorm-map'){if(current!=='Dorms')loadFloor('Dorms');setTimeout(()=>postToFloor('MAP_FLOOR_CLOSE_JACEY'),50);return;}
});
document.getElementById('mapHandbookBack').classList.add('visible');
document.getElementById('mapHandbookBack').addEventListener('click',()=>window.parent.postMessage({type:'shp:return-handbook'},'*'));
document.getElementById('exploreDormHall').addEventListener('click',()=>{const msg={type:'SHP_OPEN_LOCATION',locationId:'dorm-hall',floor:'Dorms',spawnId:null,source:'map',returnTarget:'map'};if(window.parent!==window)window.parent.postMessage(msg,'*');else window.location.href='map/explorer/dorm/index.html?mode=handbook&shpSource=map';});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>loadFloor(b.dataset.floor));search.oninput=renderList;
const requestedFloor=new URLSearchParams(location.search).get('floor');loadFloor(FLOOR_SOURCES[requestedFloor]?requestedFloor:'1F');
